name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Build (se presente)
        run: npm run build --if-present

      - name: Lint
        run: yarn lint

#      - name: Test
#        run: npm test

  lint_check:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Verificar status do linting
        run: |
          # Comando para verificar o status do linting, por exemplo:
          # Se o linting falhar, você pode usar o comando 'exit 1' para falhar a etapa
          if yarn lint; then
            echo "Linting passou."
          else
            echo "Linting falhou. Push bloqueado."
            exit 1
          fi
